"""Increase file_type field length to handle long MIME types

Revision ID: b9409383b034
Revises: 20260202_agent_orchestration
Create Date: 2026-02-04 23:16:09.264569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9409383b034'
down_revision: Union[str, None] = '20260202_agent_orchestration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_embedding_ivfflat', table_name='document_chunks', postgresql_with={'lists': '7'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_document_chunks_embedding_ivfflat', 'document_chunks', ['embedding'], unique=False, postgresql_with={'lists': '7'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
